# docker-compose.yml

version: '3.8'
services:
  credit-risk-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload 